/* Foundry -> JSON stat block export for the UE5 client.
   READ ONLY. Runs in the Foundry browser context via the playwright harness:
     EVAL=$(sed "s/__ACTOR__/Gabriel/" foundry_actor_export.js | tr '\n' ' ')
     playwright-cli eval "$EVAL"
   Authored newline-safe (every statement terminated, no line comments, no
   template literals, single quotes only) because the harness flattens this
   file to ONE line and a stray // would eat the rest of the script.
   The terrain half of the pipeline is generated by the Python tools; stat
   blocks live only in Foundry documents, so this is the other bridge. */
(() => {
  const NAME = '__ACTOR__';
  const a = game.actors.getName(NAME);
  if (!a) { return JSON.stringify({ error: 'no actor named ' + NAME }); }
  const s = a.system;

  const abilities = {};
  for (const k of Object.keys(s.abilities || {})) {
    const ab = s.abilities[k];
    abilities[k] = { value: ab.value, mod: ab.mod };
  }

  const pool = (p) => (p ? { value: p.value, max: p.max } : null);

  const def = s.defense || {};
  const defence = {
    dr: def.dr ? def.dr.value : 0,
    armor: def.armor ? def.armor.value : 0,
    veil: def.veil ? def.veil.value : 0,
    blockDR: def.blockDR || 0,
    melee: def.melee ? { value: def.melee.value, pool: def.melee.pool, poolMax: def.melee.poolMax } : null,
    ranged: def.ranged ? { value: def.ranged.value, pool: def.ranged.pool, poolMax: def.ranged.poolMax } : null,
    mind: def.mind ? { value: def.mind.value, pool: def.mind.pool, poolMax: def.mind.poolMax } : null,
    soul: def.soul ? { value: def.soul.value, pool: def.soul.pool, poolMax: def.soul.poolMax } : null
  };

  const skills = a.items.filter((i) => i.type === 'skill').map((i) => {
    const r = i.system.roll || {};
    return {
      name: i.name,
      skillType: i.system.skillType,
      reactionType: i.system.reactionType || '',
      tags: i.system.tags || [],
      affinities: i.system.affinities || [],
      rarity: i.system.rarity || '',
      requiresSight: !!i.system.requiresSight,
      aoe: i.system.aoe && i.system.aoe.enabled ? i.system.aoe : null,
      roll: {
        dice: r.dice, abilities: r.abilities, secondaryAbility: r.secondaryAbility,
        primaryWeight: r.primaryWeight, secondaryWeight: r.secondaryWeight,
        resource: r.resource, cost: r.cost,
        secondaryResource: r.secondaryResource, secondaryCost: r.secondaryCost,
        type: r.type, statType: r.statType, damageType: r.damageType,
        targetDefense: r.targetDefense, secondaryTargetDefense: r.secondaryTargetDefense,
        reach: r.reach, diceBonus: r.diceBonus,
        actionWeightMultiplier: r.actionWeightMultiplier
      }
    };
  });

  const gear = a.items.filter((i) => i.type === 'item').map((i) => ({
    name: i.name,
    equipped: !!i.system.equipped,
    weight: i.system.weight || 0,
    rarity: i.system.rarity || '',
    tags: i.system.tags || []
  }));

  return JSON.stringify({
    schema_version: 1,
    exporter: 'aop-foundry-actor-export 0.1',
    world: game.world.id,
    actor: {
      name: a.name,
      id: a.id,
      type: a.type,
      sizeTag: s.sizeTag || '',
      abilities: abilities,
      health: pool(s.health),
      mana: pool(s.mana),
      stamina: pool(s.stamina),
      overhealth: s.overhealth ? s.overhealth.value : 0,
      defence: defence,
      damageReduction: s.damageReduction || {},
      affinityMultipliers: s.affinityMultipliers || {},
      complexAffinities: s.complexAffinities || {},
      movement: {
        walkRangeFt: s.walkRange, sprintRangeFt: s.sprintRange,
        castingRangeFt: s.castingRange,
        speedMultiplier: s.movementSpeedMultiplier,
        staminaMultiplier: s.movementStaminaMultiplier
      },
      carry: {
        capacity: s.carryCapacity, weight: s.carryWeight,
        ratio: s.carryRatio, encumbered: !!s.encumbered
      },
      tags: s.tags || [],
      skillCount: skills.length,
      skills: skills,
      gear: gear
    }
  });
})
