/* Foundry -> JSON stat block export for the UE5 client.
   READ ONLY. Runs in the Foundry browser context via the playwright harness:
     EVAL=$(sed "s/__ACTOR__/Gabriel/" foundry_actor_export.js | tr '\n' ' ')
     playwright-cli eval "$EVAL"
   Authored newline-safe (every statement terminated, no line comments, no
   template literals, single quotes only) because the harness flattens this
   file to ONE line and a stray // would eat the rest of the script.
   The terrain half of the pipeline is generated by the Python tools; stat
   blocks live only in Foundry documents, so this is the other bridge. */
(() => {
  const NAME = '__ACTOR__';
  const a = game.actors.getName(NAME);
  if (!a) { return JSON.stringify({ error: 'no actor named ' + NAME }); }
  const s = a.system;

  const abilities = {};
  for (const k of Object.keys(s.abilities || {})) {
    const ab = s.abilities[k];
    abilities[k] = { value: ab.value, mod: ab.mod };
  }

  const pool = (p) => (p ? { value: p.value, max: p.max } : null);

  const def = s.defense || {};
  const defence = {
    dr: def.dr ? def.dr.value : 0,
    armor: def.armor ? def.armor.value : 0,
    veil: def.veil ? def.veil.value : 0,
    blockDR: def.blockDR || 0,
    melee: def.melee ? { value: def.melee.value, pool: def.melee.pool, poolMax: def.melee.poolMax } : null,
    ranged: def.ranged ? { value: def.ranged.value, pool: def.ranged.pool, poolMax: def.ranged.poolMax } : null,
    mind: def.mind ? { value: def.mind.value, pool: def.mind.pool, poolMax: def.mind.poolMax } : null,
    soul: def.soul ? { value: def.soul.value, pool: def.soul.pool, poolMax: def.soul.poolMax } : null
  };

  const skills = a.items.filter((i) => i.type === 'skill').map((i) => {
    const r = i.system.roll || {};
    /* The GAME resolves these; the UE port cannot (weapon match, proficiency,
       lunar phase are not in the raw fields). weaponWeight drives the hit blend,
       base stamina and windup; damageMultiplier is the resolved strike multiplier
       (authored diceBonus x proficiency, else rarity effectiveMult). Guarded: a
       non-weapon skill answers 0 weight and multiplier 1. */
    let weaponWeight = 0;
    let damageMultiplier = 1;
    try { weaponWeight = i.constructor.resolveEffectiveWeaponWeight(i, null); } catch (e) { weaponWeight = 0; }
    try {
      const db = (r.diceBonus != null) ? r.diceBonus : 1;
      damageMultiplier = (db !== 1) ? db * i._proficiencyDamageMult() : i._resolveRarityMods().effectiveMult;
    } catch (e) { damageMultiplier = 1; }
    /* DoT metadata (schema v4). Whether a skill applies a DAMAGING debuff over time is
       tagConfig.debuffDealsDamage -- a flag the tags alone do not reveal. dotScale sizes
       each tick off the parent blow; debuffDuration is the tick count. */
    const tc = i.system.tagConfig || {};
    const dotDealsDamage = !!tc.debuffDealsDamage;
    const dotScale = Number(tc.dotScale) || 0;
    const dotDuration = Number(tc.debuffDuration) || 0;
    /* TAG EFFECTS (schema v8): the combat tagConfig the UE tag engine needs, so the
       client reads NUMBERS not re-derives. The flat `tags` array (pierce/shred/crush,
       rider markers) is exported separately; this carries the parameters those tags
       are modulated by (rider trigger + gate, DR-strip/crush/melt magnitudes, the
       debuff kind, and the invest-scaled dot growth). */
    const tagEffects = {
      procTrigger: tc.procTrigger || '',
      procAttackTags: tc.procAttackTags || [],
      debuffDRStrip: !!tc.debuffDRStrip,
      debuffArmorCrush: Number(tc.debuffArmorCrush) || 0,
      crushInvestScale: Number(tc.crushInvestScale) || 0,
      debuffArmorMelt: Number(tc.debuffArmorMelt) || 0,
      debuffType: tc.debuffType || '',
      debuffDamageType: tc.debuffDamageType || '',
      dotInvestScale: Number(tc.dotInvestScale) || 0,
      /* MINE/SHRAPNEL (schema v9). mineCapacity = max concurrent mines per caster
         (mine tag, FIFO-evict). shrapnelMultiplier/Bonus size the shrapnel burst:
         a caught target is hit at rollTotal + shrapnelHitBonus and takes
         x shrapnelMultiplier damage (config shrapnelDodgePenalty is a global the
         client ports as a constant, not per-skill). */
      mineCapacity: (tc.mineCapacity == null) ? 1 : Number(tc.mineCapacity),
      shrapnelMultiplier: (tc.shrapnelMultiplier == null) ? 1 : Number(tc.shrapnelMultiplier),
      shrapnelHitBonus: Number(tc.shrapnelHitBonus) || 0
    };
    /* MAGIC (schema v5). Spell HIT and DAMAGE deliberately use different stats: hit is
       the two-stat aim (hitPrimary x0.9 + hitSecondary x0.3, the tagConfig override) and
       damage is int x mult x spellWindup(tier). We export the tier and the game-resolved
       hit blend (0 = no explicit aim override, client falls back + flags it). */
    /* AURA authoring (schema v6). A skill that emits an aura declares it on tagConfig:
       the PRE-perception radius, what it does (damage/heal/stam), its lane, who it
       hits, and the roll-scale for the per-tick payload. Null when the skill is not an
       aura. The client stretches the radius by perception and sizes the payload off the
       skill's roll, matching item.mjs's apply-time snapshot. */
    const aura = (Number(tc.auraRadius) > 0) ? {
      radius: tc.auraRadius,
      effectType: tc.auraEffectType || 'damage',
      damageType: tc.auraDamageType || 'physical',
      targeting: tc.auraTargeting || 'enemies',
      scale: (tc.auraScale == null) ? 0.3 : tc.auraScale,
      healResource: tc.auraHealResource || 'health',
      healOverhealth: !!tc.auraHealOverhealth
    } : null;

    const spellTier = r.tier || '';
    let spellHitBlend = 0;
    if (typeof r.type === 'string' && r.type.indexOf('magic') === 0) {
      const hp = tc.hitPrimary || '';
      const hs = tc.hitSecondary || '';
      const ab = s.abilities || {};
      if (hp && ab[hp]) {
        spellHitBlend = (hs && ab[hs])
          ? Math.round(ab[hp].mod * 0.9 + ab[hs].mod * 0.3)
          : ab[hp].mod;
      }
    }
    return {
      name: i.name,
      skillType: i.system.skillType,
      reactionType: i.system.reactionType || '',
      tags: i.system.tags || [],
      affinities: i.system.affinities || [],
      rarity: i.system.rarity || '',
      requiresSight: !!i.system.requiresSight,
      /* AOE FOOTPRINT (schema v9). Emit the shape even when enabled=false: a mine
         SNAPSHOTS its (disabled) aoe as the burst footprint Detonate reads back. */
      aoe: i.system.aoe ? { enabled: !!i.system.aoe.enabled, shape: i.system.aoe.shape || 'circle', diameter: Number(i.system.aoe.diameter) || 0, baseSize: Number(i.system.aoe.baseSize) || 0 } : null,
      weaponWeight: weaponWeight,
      damageMultiplier: damageMultiplier,
      dotDealsDamage: dotDealsDamage,
      dotScale: dotScale,
      dotDuration: dotDuration,
      spellTier: spellTier,
      spellHitBlend: spellHitBlend,
      aura: aura,
      tagEffects: tagEffects,
      roll: {
        dice: r.dice, abilities: r.abilities, secondaryAbility: r.secondaryAbility,
        primaryWeight: r.primaryWeight, secondaryWeight: r.secondaryWeight,
        resource: r.resource, cost: r.cost,
        secondaryResource: r.secondaryResource, secondaryCost: r.secondaryCost,
        type: r.type, statType: r.statType, damageType: r.damageType,
        targetDefense: r.targetDefense, secondaryTargetDefense: r.secondaryTargetDefense,
        reach: r.reach, diceBonus: r.diceBonus,
        actionWeightMultiplier: r.actionWeightMultiplier
      }
    };
  });

  /* INVENTORY (schema v6). Every carried item (type 'item'), equipped or not, with
     its GAME-RESOLVED per-item contribution read straight off the stored derived fields
     (statBonuses/armorBonus/veilBonus/damageReduction/damageBonus -- the auto-derive hook
     has already baked augments/material/rarity into these, which is exactly what
     equipment.mjs reads when it builds the equip ActiveEffects). The client backs out a
     base from the actor's loadout-inclusive stats and applies +/- these on equip. */
  const inventory = a.items.filter((i) => i.type === 'item').map((i) => {
    const it = i.system || {};
    const dr = it.damageReduction || {};
    const sb = (it.statBonuses || []).map((b) => ({ ability: b.ability, value: b.value }));
    return {
      id: i.id,
      name: i.name,
      slot: it.slot || '',
      hand: it.hand || '',
      twoHanded: !!it.twoHanded,
      equipped: !!it.equipped,
      weight: it.weight || 0,
      quantity: (it.quantity == null) ? 1 : it.quantity,
      rarity: it.rarity || '',
      material: it.material || '',
      storedIn: it.storedIn || '',
      spatialCapacity: it.spatialCapacity || 0,
      statBonuses: sb,
      armorBonus: it.armorBonus || 0,
      veilBonus: it.veilBonus || 0,
      drPhysical: dr.physical || 0,
      drMagical: dr.magical || 0,
      damageBonus: it.damageBonus || 0
    };
  });

  /* FOLDER (schema v7): the actor's Foundry directory path (ancestors joined by '/'),
     so the client can group the spawn picker by the same folders the GM organizes in
     Foundry. Empty when the actor is unfiled. */
  let folderPath = '';
  if (a.folder) {
    const parts = [];
    let f = a.folder;
    while (f) { parts.unshift(f.name); f = f.folder; }
    folderPath = parts.join('/');
  }

  return JSON.stringify({
    schema_version: 9,
    exporter: 'aop-foundry-actor-export 0.9',
    world: game.world.id,
    actor: {
      name: a.name,
      id: a.id,
      type: a.type,
      sizeTag: s.sizeTag || '',
      folder: folderPath,
      raceRank: (s.attributes && s.attributes.race && s.attributes.race.rank) ? s.attributes.race.rank : 'E',
      abilities: abilities,
      health: pool(s.health),
      mana: pool(s.mana),
      stamina: pool(s.stamina),
      overhealth: s.overhealth ? s.overhealth.value : 0,
      defence: defence,
      damageReduction: s.damageReduction || {},
      affinityMultipliers: s.affinityMultipliers || {},
      complexAffinities: s.complexAffinities || {},
      movement: {
        walkRangeFt: s.walkRange, sprintRangeFt: s.sprintRange,
        castingRangeFt: s.castingRange,
        speedMultiplier: s.movementSpeedMultiplier,
        staminaMultiplier: s.movementStaminaMultiplier
      },
      carry: {
        capacity: s.carryCapacity, weight: s.carryWeight,
        ratio: s.carryRatio, encumbered: !!s.encumbered
      },
      tags: s.tags || [],
      skillCount: skills.length,
      skills: skills,
      inventory: inventory
    }
  });
})
