/* Foundry -> JSON stat block export for the UE5 client.
   READ ONLY. Runs in the Foundry browser context via the playwright harness:
     EVAL=$(sed "s/__ACTOR__/Gabriel/" foundry_actor_export.js | tr '\n' ' ')
     playwright-cli eval "$EVAL"
   Authored newline-safe (every statement terminated, no line comments, no
   template literals, single quotes only) because the harness flattens this
   file to ONE line and a stray // would eat the rest of the script.
   The terrain half of the pipeline is generated by the Python tools; stat
   blocks live only in Foundry documents, so this is the other bridge. */
(() => {
  const NAME = '__ACTOR__';
  const a = game.actors.getName(NAME);
  if (!a) { return JSON.stringify({ error: 'no actor named ' + NAME }); }
  const s = a.system;

  const abilities = {};
  for (const k of Object.keys(s.abilities || {})) {
    const ab = s.abilities[k];
    /* value = the DERIVED final (titles, blessings, capped equipment, effects); base = the
       stored source value the derivation starts from (v12.1, for the UE derivation port). */
    const src = (a._source && a._source.system && a._source.system.abilities && a._source.system.abilities[k]) ? a._source.system.abilities[k] : null;
    abilities[k] = { value: ab.value, mod: ab.mod, base: src ? Math.round(src.value || 0) : ab.value };
  }

  const pool = (p) => (p ? { value: p.value, max: p.max } : null);

  const def = s.defense || {};
  const defence = {
    dr: def.dr ? def.dr.value : 0,
    armor: def.armor ? def.armor.value : 0,
    veil: def.veil ? def.veil.value : 0,
    blockDR: def.blockDR || 0,
    melee: def.melee ? { value: def.melee.value, pool: def.melee.pool, poolMax: def.melee.poolMax } : null,
    ranged: def.ranged ? { value: def.ranged.value, pool: def.ranged.pool, poolMax: def.ranged.poolMax } : null,
    mind: def.mind ? { value: def.mind.value, pool: def.mind.pool, poolMax: def.mind.poolMax } : null,
    soul: def.soul ? { value: def.soul.value, pool: def.soul.pool, poolMax: def.soul.poolMax } : null
  };

  const mapSkill = (i) => {
    const r = i.system.roll || {};
    /* The GAME resolves these; the UE port cannot (weapon match, proficiency,
       lunar phase are not in the raw fields). weaponWeight drives the hit blend,
       base stamina and windup; damageMultiplier is the resolved strike multiplier
       (authored diceBonus x proficiency, else rarity effectiveMult). Guarded: a
       non-weapon skill answers 0 weight and multiplier 1. */
    let weaponWeight = 0;
    let damageMultiplier = 1;
    try { weaponWeight = i.constructor.resolveEffectiveWeaponWeight(i, null); } catch (e) { weaponWeight = 0; }
    try {
      const db = (r.diceBonus != null) ? r.diceBonus : 1;
      damageMultiplier = (db !== 1) ? db * i._proficiencyDamageMult() : i._resolveRarityMods().effectiveMult;
    } catch (e) { damageMultiplier = 1; }
    /* v12.4 (additive): the PROFICIENCY halves baked into damageMultiplier, and the weapon the
       game resolved for this skill on export day, so the UE client can re-resolve them LIVE
       when the hands change (AoPStyles): live = exported / profDamageMult x liveProf. */
    let profDamageMult = 1, profHitMult = 1, weaponType = '';
    try {
      const WS = game.aspectsofpower && game.aspectsofpower.weaponStyles;
      const held = i._proficiencyWeapon ? i._proficiencyWeapon() : null;
      profDamageMult = i._proficiencyDamageMult ? (i._proficiencyDamageMult() || 1) : 1;
      if (WS && WS.proficiencyHitMult && (CONFIG.ASPECTSOFPOWER.weaponProficiency.rollTypes || []).indexOf(r.type) >= 0) { profHitMult = WS.proficiencyHitMult(a, held) || 1; }
      if (WS && WS.weaponTypesOfItem && held) { const wt = WS.weaponTypesOfItem(held); weaponType = wt && wt.length ? wt[0] : ''; }
    } catch (e) { profDamageMult = 1; profHitMult = 1; weaponType = ''; }
    /* DoT metadata (schema v4). Whether a skill applies a DAMAGING debuff over time is
       tagConfig.debuffDealsDamage -- a flag the tags alone do not reveal. dotScale sizes
       each tick off the parent blow; debuffDuration is the tick count. */
    const tc = i.system.tagConfig || {};
    const dotDealsDamage = !!tc.debuffDealsDamage;
    const dotScale = Number(tc.dotScale) || 0;
    const dotDuration = Number(tc.debuffDuration) || 0;
    /* TAG EFFECTS (schema v8): the combat tagConfig the UE tag engine needs, so the
       client reads NUMBERS not re-derives. The flat `tags` array (pierce/shred/crush,
       rider markers) is exported separately; this carries the parameters those tags
       are modulated by (rider trigger + gate, DR-strip/crush/melt magnitudes, the
       debuff kind, and the invest-scaled dot growth). */
    const tagEffects = {
      procTrigger: tc.procTrigger || '',
      procAttackTags: tc.procAttackTags || [],
      debuffDRStrip: !!tc.debuffDRStrip,
      debuffArmorCrush: Number(tc.debuffArmorCrush) || 0,
      crushInvestScale: Number(tc.crushInvestScale) || 0,
      debuffArmorMelt: Number(tc.debuffArmorMelt) || 0,
      debuffType: tc.debuffType || '',
      debuffDamageType: tc.debuffDamageType || '',
      dotInvestScale: Number(tc.dotInvestScale) || 0,
      /* MINE/SHRAPNEL (schema v9). mineCapacity = max concurrent mines per caster
         (mine tag, FIFO-evict). shrapnelMultiplier/Bonus size the shrapnel burst:
         a caught target is hit at rollTotal + shrapnelHitBonus and takes
         x shrapnelMultiplier damage (config shrapnelDodgePenalty is a global the
         client ports as a constant, not per-skill). */
      mineCapacity: (tc.mineCapacity == null) ? 1 : Number(tc.mineCapacity),
      shrapnelMultiplier: (tc.shrapnelMultiplier == null) ? 1 : Number(tc.shrapnelMultiplier),
      shrapnelHitBonus: Number(tc.shrapnelHitBonus) || 0
    };
    /* MAGIC (schema v5). Spell HIT and DAMAGE deliberately use different stats: hit is
       the two-stat aim (hitPrimary x0.9 + hitSecondary x0.3, the tagConfig override) and
       damage is int x mult x spellWindup(tier). We export the tier and the game-resolved
       hit blend (0 = no explicit aim override, client falls back + flags it). */
    /* AURA authoring (schema v6). A skill that emits an aura declares it on tagConfig:
       the PRE-perception radius, what it does (damage/heal/stam), its lane, who it
       hits, and the roll-scale for the per-tick payload. Null when the skill is not an
       aura. The client stretches the radius by perception and sizes the payload off the
       skill's roll, matching item.mjs's apply-time snapshot. */
    const aura = (Number(tc.auraRadius) > 0) ? {
      radius: tc.auraRadius,
      effectType: tc.auraEffectType || 'damage',
      damageType: tc.auraDamageType || 'physical',
      targeting: tc.auraTargeting || 'enemies',
      scale: (tc.auraScale == null) ? 0.3 : tc.auraScale,
      healResource: tc.auraHealResource || 'health',
      healOverhealth: !!tc.auraHealOverhealth
    } : null;

    const spellTier = r.tier || '';
    let spellHitBlend = 0;
    if (typeof r.type === 'string' && r.type.indexOf('magic') === 0) {
      const hp = tc.hitPrimary || '';
      const hs = tc.hitSecondary || '';
      const ab = s.abilities || {};
      if (hp && ab[hp]) {
        spellHitBlend = (hs && ab[hs])
          ? Math.round(ab[hp].mod * 0.9 + ab[hs].mod * 0.3)
          : ab[hp].mod;
      }
    }
    return {
      name: i.name,
      skillType: i.system.skillType,
      ritualGrade: i.system.ritualGrade || 'E',
      favorite: !!i.system.favorite,
      craftBonuses: (i.system.craftBonuses || []).map(function (b) { return { type: b.type || '', value: b.value == null ? 0 : b.value, affinity: b.affinity || '' }; }),
      craftAllowedTypes: Array.isArray(i.system.craftAllowedTypes) ? i.system.craftAllowedTypes.slice() : [],
      /* v12.6: which AUGMENT document an `augment` skill applies (flags), or the engrave dispatch. */
      appliesAugmentId: (i.flags && i.flags.aspectsofpower && i.flags.aspectsofpower.appliesAugmentId) || '',
      engraveDispatch: !!(i.flags && i.flags.aspectsofpower && i.flags.aspectsofpower.engraveDispatch),
      img: i.img || '',
      reactionType: i.system.reactionType || '',
      tags: i.system.tags || [],
      affinities: i.system.affinities || [],
      rarity: i.system.rarity || '',
      requiresSight: !!i.system.requiresSight,
      /* AOE FOOTPRINT (schema v9; v11 adds angle/width/targetingMode for cone/ray + friendly-fire).
         Emit the shape even when enabled=false: a mine SNAPSHOTS its (disabled) aoe as the burst
         footprint Detonate reads back. */
      aoe: i.system.aoe ? { enabled: !!i.system.aoe.enabled, shape: i.system.aoe.shape || 'circle', diameter: Number(i.system.aoe.diameter) || 0, baseSize: Number(i.system.aoe.baseSize) || 0, angle: Number(i.system.aoe.angle) || 0, width: Number(i.system.aoe.width) || 0, targetingMode: i.system.aoe.targetingMode || 'all', templateDuration: Number(i.system.aoe.templateDuration) || 0, zoneEffect: i.system.aoe.zoneEffect || 'none' } : null,
      /* TAG CONFIG passthrough (schema v11): the skill's flat tagConfig map, pruned to SET (truthy)
         entries, into the client's generic TagConfigRaw -- the same store UE-authored skills use.
         Unlocks guardianMode/redirectPct, reaction*, summon*, ... without a per-field schema each time.
         Objects/arrays are JSON-stringified; the client reads the keys it needs. */
      id: i.id,
      tagConfig: (function () { var o = {}; var keys = Object.keys(tc); for (var ki = 0; ki < keys.length; ki++) { var k = keys[ki]; var v = tc[k]; if (v === 0 || v === '' || v === false || v === null || v === undefined) { continue; } if (Array.isArray(v) && v.length === 0) { continue; } o[k] = (typeof v === 'object') ? JSON.stringify(v) : v; } return o; })(),
      weaponWeight: weaponWeight,
      damageMultiplier: damageMultiplier,
      profDamageMult: profDamageMult,
      profHitMult: profHitMult,
      weaponType: weaponType,
      dotDealsDamage: dotDealsDamage,
      dotScale: dotScale,
      dotDuration: dotDuration,
      spellTier: spellTier,
      spellHitBlend: spellHitBlend,
      aura: aura,
      tagEffects: tagEffects,
      roll: {
        dice: r.dice, abilities: r.abilities, secondaryAbility: r.secondaryAbility,
        primaryWeight: r.primaryWeight, secondaryWeight: r.secondaryWeight,
        resource: r.resource, cost: r.cost,
        secondaryResource: r.secondaryResource || '', secondaryCost: r.secondaryCost || 0,
        secondaryResource: r.secondaryResource, secondaryCost: r.secondaryCost,
        type: r.type, statType: r.statType, damageType: r.damageType,
        targetDefense: r.targetDefense, secondaryTargetDefense: r.secondaryTargetDefense,
        reach: r.reach, diceBonus: r.diceBonus,
        actionWeightMultiplier: r.actionWeightMultiplier
      }
    };
  };
  const skills = a.items.filter((i) => i.type === 'skill').map(mapSkill);
  /* v12.8: RITUAL ACTIVATION SKILLS. A ritual's tagConfig.ritualActivationSkillId may name a
     compendium skill the actor does not own (Place Lightstream Prism); an inscribed gem fires it.
     Export those alongside the actor's skills, marked activationOnly so the client keeps them off
     the hotbar and out of the AI pick. fromUuidSync needs the pack loaded (the batch harness
     preloads every skills compendium). */
  for (const rs of a.items.filter((i) => i.type === 'skill' && (i.system.tags || []).includes('ritual'))) {
    const actId = rs.system.tagConfig && rs.system.tagConfig.ritualActivationSkillId;
    if (!actId) { continue; }
    let act = null;
    try { act = fromUuidSync(actId); } catch (e) { act = null; }
    if (!act || act.type !== 'skill') { continue; }
    /* The actor already OWNS the activation (a lunar ritual's activation is the granted skill
       itself): stamp the owned copy with the uuid so an inscribed gem can find it. */
    if (a.items.getName(act.name)) { const own = skills.find((k) => !k.activationOnly && k.name === act.name); if (own && !own.activationUuid) { own.activationUuid = actId; } continue; }
    if (skills.some((k) => k.activationOnly && k.name === act.name)) { continue; }
    const mapped = mapSkill(act);
    mapped.activationOnly = true;
    mapped.activationUuid = actId;
    skills.push(mapped);
  }

  /* INVENTORY (schema v6). Every carried item (type 'item'), equipped or not, with
     its GAME-RESOLVED per-item contribution read straight off the stored derived fields
     (statBonuses/armorBonus/veilBonus/damageReduction/damageBonus -- the auto-derive hook
     has already baked augments/material/rarity into these, which is exactly what
     equipment.mjs reads when it builds the equip ActiveEffects). The client backs out a
     base from the actor's loadout-inclusive stats and applies +/- these on equip. */
  const inventory = a.items.filter((i) => i.type === 'item').map((i) => {
    const it = i.system || {};
    const dr = it.damageReduction || {};
    const sb = (it.statBonuses || []).map((b) => ({ ability: b.ability, value: b.value }));
    return {
      id: i.id,
      name: i.name,
      img: i.img || '',
      slot: it.slot || '',
      hand: it.hand || '',
      twoHanded: !!it.twoHanded,
      equipped: !!it.equipped,
      weight: it.weight || 0,
      quantity: (it.quantity == null) ? 1 : it.quantity,
      rarity: it.rarity || '',
      material: it.material || '',
      storedIn: it.storedIn || '',
      spatialCapacity: it.spatialCapacity || 0,
      wovenAffinities: Array.isArray(it.wovenAffinities) ? it.wovenAffinities : [],
      weaveAttuned: it.weaveAttuned || '',
      deployStub: (function () { if (!it.deployStubActorUuid) { return ''; } var st = null; try { st = fromUuidSync(it.deployStubActorUuid); } catch (e) { st = null; } return (st && st.name) ? st.name : ''; })(),
      onKillGained: (i.flags && i.flags.aspectsofpower && i.flags.aspectsofpower.onKillProgressGained) || 0,
      statBonuses: sb,
      armorBonus: it.armorBonus || 0,
      veilBonus: it.veilBonus || 0,
      drPhysical: dr.physical || 0,
      drMagical: dr.magical || 0,
      damageBonus: it.damageBonus || 0,
      /* v12.3 (additive): the CRAFTING fields -- a material's progress/cap/element/grade and a
         crafted piece's progress ceiling + rework count, so the UE craft port can consume
         materials and derive products exactly as crafting-skills.mjs does. */
      isMaterial: !!it.isMaterial,
      progress: it.progress || 0,
      maxProgress: it.maxProgress || 0,
      materialElement: it.materialElement || '',
      materialGrade: it.materialGrade || 'E',
      materialCap: it.materialCap || 0,
      reworkCount: it.reworkCount || 0,
      /* v12.5 (additive): durability -- max 0 = untracked (conjured / legacy gear never wears). */
      durability: (it.durability && it.durability.value) || 0,
      durabilityMax: (it.durability && it.durability.max) || 0,
      /* v12.6 (additive): augment sockets -- combat and profession slot totals and how many are
         filled (the fills' bonuses are already baked into the derived fields above). */
      augmentSlots: it.augmentSlots || 0,
      profAugmentSlots: it.profAugmentSlots || 0,
      augmentsUsed: (it.augments || []).filter(function (e) { return e && e.augmentId; }).length,
      profAugmentsUsed: (it.profAugments || []).filter(function (e) { return e && e.augmentId; }).length,
      /* v10: the item's unified tag list (weapon/armor/material tags). A SHIELD is any item
         whose tags include 'shield' (buckler/greatshield subtypes come along) -- drives block/bulwark.
         Block comment (not //) so the one-line flatten harness does not eat the rest of the script. */
      tags: Array.isArray(it.tags) ? it.tags.slice() : []
    };
  });

  /* FOLDER (schema v7): the actor's Foundry directory path (ancestors joined by '/'),
     so the client can group the spawn picker by the same folders the GM organizes in
     Foundry. Empty when the actor is unfiled. */
  let folderPath = '';
  if (a.folder) {
    const parts = [];
    let f = a.folder;
    while (f) { parts.unshift(f.name); f = f.folder; }
    folderPath = parts.join('/');
  }

  /* AI FLAGS (schema v11): the authored brain + faculties (flags.aspectsofpower.aiProfile /
     aiBehaviors), so the client drives an AI actor by its authored profile instead of a loadout
     heuristic. Empty when unset (the client then derives). */
  var aiFlags = (a.flags && a.flags.aspectsofpower) ? a.flags.aspectsofpower : {};
  var aiProfile = aiFlags.aiProfile || '';
  var aiBehaviors = Array.isArray(aiFlags.aiBehaviors) ? aiFlags.aiBehaviors.slice() : [];

  /* EFFECTS (schema v12): the actor's ActiveEffects with their category -- TITLES (additive
     to base), BLESSINGS (multiply), passives, temporary buffs/debuffs -- and their stat
     changes, so the client sheet shows Titles / Blessings and reads what each one does. */
  /* allApplicableEffects, not a.effects: racial passives (Scaled Hide, Eagle Eye) and other
     item-carried effects transfer from embedded items and never sit on the actor itself. */
  var effects = Array.from(a.allApplicableEffects()).map(function (e) {
    var es = e.system || {};
    return {
      id: e.id,
      name: e.name,
      img: e.img || '',
      category: es.effectCategory || '',
      effectType: es.effectType || '',
      itemSource: es.itemSource || '',
      disabled: !!e.disabled,
      roundsRemaining: (es.roundsRemaining == null) ? -1 : es.roundsRemaining,
      changes: (e.changes || []).map(function (c) { return { key: c.key, mode: c.mode, type: c.type || '', value: String(c.value) }; })
    };
  });

  /* CONSUMABLES (schema v12): items of type 'consumable' with the effect block that matters
     for their consumableType (restoration / buff / poison / barrier / bomb / repair). */
  var consumables = a.items.filter(function (i) { return i.type === 'consumable'; }).map(function (i) {
    var c = i.system || {};
    var ch = c.charges || {};
    var rs = c.restoration || {};
    var bf = c.buff || {};
    var po = c.poison || {};
    var ba = c.barrier || {};
    var bo = c.bomb || {};
    return {
      id: i.id,
      name: i.name,
      img: i.img || '',
      consumableType: c.consumableType || '',
      effectType: c.effectType || '',
      quantity: (c.quantity == null) ? 1 : c.quantity,
      weight: c.weight || 0,
      rarity: c.rarity || '',
      chargesValue: (ch.value == null) ? 1 : ch.value,
      chargesMax: (ch.max == null) ? 1 : ch.max,
      restoreResource: rs.resource || '',
      restoreAmount: rs.amount || 0,
      restoreOverhealth: !!rs.overhealth,
      buffEntries: (bf.entries || []).map(function (b) { return { attribute: b.attribute, value: b.value }; }),
      buffDuration: bf.duration || 0,
      poisonDamage: po.damage || 0,
      poisonDamageType: po.damageType || '',
      poisonDuration: po.duration || 0,
      barrierValue: ba.value || 0,
      bombDamage: bo.damage || 0,
      bombDamageType: bo.damageType || '',
      bombShape: bo.shape || '',
      bombDiameter: bo.diameter || 0,
      repairAmount: c.repairAmount || 0,
      ritualSkillId: c.ritualSkillId || '',
      ritualPower: c.ritualPower || 0,
      mediumType: c.mediumType || ''
    };
  });

  /* RECIPES (schema v12): known recipes -- the bill of materials, threshold, product. */
  var recipes = a.items.filter(function (i) { return i.type === 'recipe'; }).map(function (i) {
    var r = i.system || {};
    var out = r.output || {};
    return {
      id: i.id,
      name: i.name,
      img: i.img || '',
      profession: r.profession || '',
      rarity: r.rarity || '',
      threshold: r.threshold || 0,
      minMana: r.minMana || 0,
      source: r.source || '',
      discoveredBy: r.discoveredBy || '',
      requiresSkillTags: Array.isArray(r.requiresSkillTags) ? r.requiresSkillTags.slice() : [],
      inputs: (r.inputs || []).map(function (n) { return { material: n.material || '', itemName: n.itemName || '', element: n.element || '', quantity: n.quantity || 1, minProgress: n.minProgress || 0 }; }),
      outputName: out.name || '',
      outputTags: Array.isArray(out.tags) ? out.tags.slice() : [],
      outputTypeKey: out.typeKey || '',
      outputMaterial: out.material || '',
      outputElement: out.element || '',
      outputQuantity: out.quantity || 1
    };
  });

  return JSON.stringify({
    schema_version: 12,
    exporter: 'aop-foundry-actor-export 0.12',
    world: game.world.id,
    actor: {
      name: a.name,
      id: a.id,
      type: a.type,
      sizeTag: s.sizeTag || '',
      folder: folderPath,
      aiProfile: aiProfile,
      aiBehaviors: aiBehaviors,
      raceRank: (s.attributes && s.attributes.race && s.attributes.race.rank) ? s.attributes.race.rank : 'E',
      raceName: (s.attributes && s.attributes.race) ? (s.attributes.race.name || '') : '',
      className: (s.attributes && s.attributes['class']) ? (s.attributes['class'].name || '') : '',
      professionName: (s.attributes && s.attributes.profession) ? (s.attributes.profession.name || '') : '',
      levels: {
        race: (s.attributes && s.attributes.race) ? (s.attributes.race.level || 0) : 0,
        'class': (s.attributes && s.attributes['class']) ? (s.attributes['class'].level || 0) : 0,
        profession: (s.attributes && s.attributes.profession) ? (s.attributes.profession.level || 0) : 0
      },
      strain: s.strain || 0,
      freePoints: s.freePoints || 0,
      credits: s.credits || 0,
      activeLoadout: s.activeLoadout || 'combat',
      /* v12.6: the engravings this actor has learned (engraveDispatch augment skills pick among them). */
      knownEngraves: (a.flags && a.flags.aspectsofpower && Array.isArray(a.flags.aspectsofpower.knownEngraves)) ? a.flags.aspectsofpower.knownEngraves.slice() : [],
      abilities: abilities,
      health: pool(s.health),
      mana: pool(s.mana),
      stamina: pool(s.stamina),
      overhealth: s.overhealth ? s.overhealth.value : 0,
      defence: defence,
      damageReduction: s.damageReduction || {},
      affinityMultipliers: s.affinityMultipliers || {},
      complexAffinities: s.complexAffinities || {},
      movement: {
        walkRangeFt: s.walkRange, sprintRangeFt: s.sprintRange,
        castingRangeFt: s.castingRange,
        speedMultiplier: s.movementSpeedMultiplier,
        staminaMultiplier: s.movementStaminaMultiplier
      },
      carry: {
        capacity: s.carryCapacity, weight: s.carryWeight,
        ratio: s.carryRatio, encumbered: !!s.encumbered
      },
      /* v12.7: the COLLECTED tag set (actor._collectTags: race/class/profession cachedTags +
         system.tags + equipped item tags + implied tags) -- what hasTag() actually answers. The
         bare system.tags missed every template-conferred gate (ki, healer, no-magic ...). */
      tags: (s.collectedTags && typeof s.collectedTags.keys === 'function') ? Array.from(s.collectedTags.keys()) : (s.tags || []),
      systemTags: s.tags || [],
      /* v12.7: the KI pool (kiMaxFor(endurance) when the ki tag is held; earned on a pierce, spent
         by ki-resource skills, a quarter back per hour of meditation). */
      ki: { value: (s.ki && s.ki.value) || 0, max: (s.ki && s.ki.max) || 0 },
      skillCount: skills.length,
      skills: skills,
      inventory: inventory,
      effects: effects,
      consumables: consumables,
      recipes: recipes
    }
  });
})
